# semantic-release configuration for Python projects
# See: https://semantic-release.gitbook.io/semantic-release/

branches:
  - main

plugins:
  # Analyze commits to determine version bump
  - "@semantic-release/commit-analyzer"

  # Generate release notes from commits
  - "@semantic-release/release-notes-generator"

  # Update CHANGELOG.md
  - - "@semantic-release/changelog"
    - changelogFile: CHANGELOG.md

  # Update pyproject.toml version and build
  - - "@semantic-release/exec"
    - prepareCmd: |
        sed -i.bak 's/^version = ".*"/version = "${nextRelease.version}"/' pyproject.toml && \
        rm -f pyproject.toml.bak

  # Commit version changes
  - - "@semantic-release/git"
    - assets:
        - pyproject.toml
        - CHANGELOG.md
      message: "chore(release): ${nextRelease.version} [skip ci]"

  # Push changes and tags
  - - "@semantic-release/exec"
    - successCmd: |
        git push --follow-tags origin main

  # Create GitHub release
  - "@semantic-release/github"
